# Generated by Django 5.1 on 2024-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_dec', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
