# Generated by Django 5.1 on 2024-09-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_dec',
            new_name='product_desc',
        ),
    ]
