# Generated by Django 5.1 on 2024-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='john.doe@gmail.com', max_length=200),
        ),
    ]
